GDC-1199: Перенести и отрефакторить виджет Stats
consta-design-system/widgets pull request #1
Opened 2021-02-09 07:58 UTC by al-fyodorov

## Чек-лист
- [ ] Используются размеры/цвета/шрифты/иконки/компоненты из UI-kit
- [ ] Написаны тесты на новые/измененные расчёты
- [ ] Заведена задача на повышение версии компонентов, если нужно будет где-то их обновить
- [ ] Оставлены комментарии в тех местах, где требуется пояснить, почему было принято такое решение

2021-02-09 07:59 UTC, al-fyodorov commented on .stylelintrc.js
> +    'selector-class-pattern': '[a-zA-Z0-9_-]+',
Пока добавил так, потому что модификаторы добавлять было нельзя.

2021-02-09 08:03 UTC, al-fyodorov commented on webpack/helpers.js
> +  disableCSSModules(config) {
@gizeasy, есть замечание, не достаточно просто скопировать проект, поправить конфиги и не проверить результат. Конкретно в этом случае мы получили абсолютно сломанный Storybook из-за того что не обрабатывались MDX файлы, кроме того ты добавил `@bem-react/classnames`, но не проверил работает он или нет, в проекте по умолчанию использовались CSS Modules, и все равно генерировались другие имена классов из-за чего твое решение не работало.

2021-02-09 08:07 UTC, al-fyodorov commented on webpack/helpers.js
> +  disableCSSModules(config) {
Выпустил несколько фиксов для того чтобы ваша идея определения компонентов по БЭМ работала. Если есть какие-то еще инфраструктурные вещи или требования в проекте, то опиши их в документации и сразу донастрой проект так как ваша команда считает правильным.

В наши планы и договоренности по проекту не входила доработка конфигов и настройка генерации классов по БЭМ.

2021-02-09 08:09 UTC, al-fyodorov commented
@gizeasy еще надо настроить в репозитории генерацию ссылок на Jira (делается в настройках) или выпилить danger так как сейчас в PR есть упоминание задачи, но нет на нее ссылки.

2021-02-09 10:40 UTC, gizeasy commented on webpack/helpers.js
> +  disableCSSModules(config) {
Спасибо.

Влил донастрой проекта.

2021-02-09 10:42 UTC, gizeasy commented on webpack/helpers.js
> +  disableCSSModules(config) {
удалил danger

2021-02-10 08:16 UTC, typeetfunc approved these changes

2021-02-11 06:43 UTC, gizeasy requested changes

2021-02-11 06:43 UTC, gizeasy commented on src/Stats/__stories__/Stats.mdx
> +| [`withSign?`](#плюс-в-начале)       | `boolean`                                 | -            | Добавляет плюс перед числом
У дизайнеров спросил про это свойство. По моему хотели просто строку прокидывать.

2021-02-11 06:49 UTC, MariaLakomkina commented on src/Stats/__stories__/Stats.mdx
> +| [`withSign?`](#плюс-в-начале)       | `boolean`                                 | -            | Добавляет плюс перед числом
Да, хотели просто строку, в которую что пришло, то и отобразилось. Модификатор withSign, который добавляет плюс нужно убрать. В доке, в ноушене по статам писала об этом. А остальные элементы в этот PR не вошли еще — иконки стрелок и цифры вместо бейджа?

2021-02-11 07:00 UTC, gizeasy requested changes

2021-02-11 07:00 UTC, gizeasy commented on src/Stats/index.ts
> +export * from './Stats'
Предпологалось что все компоненты  будут лежать в папке __private__ и все что хотим вынести на ружу будем реэкспортить из __private__. Думал сделать так ради того чтобы когда появятся компоненты которые не надо было делать публичными, лежали бы в месте с теми-же компонентами которые публичными. А так получается что часть кода в одном месте часть в другом.

2021-02-11 08:57 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.mdx
> +| [`withSign?`](#плюс-в-начале)       | `boolean`                                 | -            | Добавляет плюс перед числом
@gizeasy тут только перенос и рефакторинг на БЭМ, переделка пропсов это уже другая задача.

2021-02-11 08:58 UTC, gizeasy commented on src/Stats/__stories__/Stats.mdx
> +| [`withSign?`](#плюс-в-начале)       | `boolean`                                 | -            | Добавляет плюс перед числом
понял

2021-02-11 09:22 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.mdx
> +| [`withSign?`](#плюс-в-начале)       | `boolean`                                 | -            | Добавляет плюс перед числом
@MariaLakomkina, эти доработки будут, но не в текущей задаче. Работа над виджетами разбита на задачи/этапы, которые позволяюь вносить небольшие полностью функциональные правки и получить результаты на всем этапе работы. Если пытаться сделать компонент сразу по всем требованиям это значительно затянется во времени, и заказчик не будет видеть результат работы пока не пройдет еще несколько итераций тестирования после разработки.

2021-02-11 09:25 UTC, gizeasy approved these changes

2021-02-11 09:25 UTC, al-fyodorov commented on src/Stats/index.ts
> +export * from './Stats'
Договорились пока оставить как есть.

2021-02-11 09:27 UTC, merged

2021-02-16 17:41 UTC, MariaLakomkina commented
+