feat(LinearChart): update linear chart
consta-design-system/widgets pull request #17
Opened 2021-02-20 08:27 UTC by karpovfv-nedra

## Описание изменений

Внесение правок по Linear Chart компоненту

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-20 08:41 UTC, karpovfv-nedra commented
Большинство правок по замечениям из пулл реквеста https://github.com/gazprom-neft/consta-widgets-new/pull/3 сделал.

Добавил ещё функцию `onItemClick` для легенд айтемов, подумал что возможно пригодится на будущее. Всем функциям мыши (onMouseEnter, onMouseLeave, onClick) прокинул событие мыши ещё.

В `LineTooltip.tsx ` там уже используется в свойствах, это дефолтные подписи на случай, если пользователь не укажет ничего
> давай эти слова вынесем в свойства компонента


========================================

Остались вопросы по некоторым пунктам:

1) Мы сейчас оставляем в `LegendItem` только отображение точки (dot) и возможность самому прокидывать иконку через `renderLeftSide: () => ReactNode` ? Линию тоже убираем? Не понял в итоге что мы оставляем, а что убираем..

2) Не понял момент в `LegendItem.tsx` про:
> давай задавать ccs переменную --icon-color у рутового компонента
и в css уже куда надо туда ее и прокидывать

3) Я бы создал отдельной задачей переписать функции из `lodash` на свои в utils, так как этих функций немало используется в коде линеар и бар чартов, и других необходимых компонентах.

2021-02-24 08:35 UTC, gizeasy commented
> Большинство правок по замечениям из пулл реквеста #3 сделал.
> 
> Добавил ещё функцию `onItemClick` для легенд айтемов, подумал что возможно пригодится на будущее. Всем функциям мыши (onMouseEnter, onMouseLeave, onClick) прокинул событие мыши ещё.
> 
> В `LineTooltip.tsx ` там уже используется в свойствах, это дефолтные подписи на случай, если пользователь не укажет ничего
> 
> > давай эти слова вынесем в свойства компонента
> 
> ========================================
> 
> Остались вопросы по некоторым пунктам:
> 
> 1. Мы сейчас оставляем в `LegendItem` только отображение точки (dot) и возможность самому прокидывать иконку через `renderLeftSide: () => ReactNode` ? Линию тоже убираем? Не понял в итоге что мы оставляем, а что убираем..
> 2. Не понял момент в `LegendItem.tsx` про:
> 
> > давай задавать ccs переменную --icon-color у рутового компонента
> > и в css уже куда надо туда ее и прокидывать
> 
> 1. Я бы создал отдельной задачей переписать функции из `lodash` на свои в utils, так как этих функций немало используется в коде линеар и бар чартов, и других необходимых компонентах.

1) линию и точку оставьте, renderLeftSide на случай если потребуется передать что-то  свое
2) суть в том чтобы передавать в `style={{'--color-icon': color}}` и в css уже эту переменную использовать в одном случае как `background`, в другом как `color`
3) давай

2021-02-24 08:58 UTC, schurf-des commented
Привет, по дизайну было бы хорошо поправить пару моментов.

#### Оформление всех чисел
- [ ] Точки вместо запятых в дробях
- [ ] Дефисы вместо минусов
- [ ] От четырех знаков должен быть пробел
- [ ] Числа не переводятся в экспоненциальную форму
- [ ] у подписей шкалы всегда одинаковая разрядность. Если хотя бы у одного значения шкалы есть дробная часть, точно такая же есть у остальных.

см. [https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=2202%3A4014](https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=2202%3A4014)

#### Тултип
- [ ] инвертировать тему тултипа. дефолт для дисплея и дарка, дарк для дефолта
- [ ] Предел отображается в тултипе без шарика с цветом
- [ ] зона ховера должна быть больше, чем линия или точка. 50% от величины шага.

#### Прочее оформительство
- [ ] размер точек, r=2.5 → 3
- [ ] расстояние от сетки до нижней шкалы xs (8)
- [ ] расстояние от сетки до боковой шкалы xs
- [ ] если есть куда скроллить, с нужной стороны должна быть тень
[https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=295%3A4](https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=295%3A4)
- [ ] Если линия расходится от нуля, сейчас рисуется один общий градиент, нужно два разных
[https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=1599%3A59](https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=1599%3A59)

#### limitMinimumStepSize и шкала
Когда limitMinimumStepSize отключен, логично, что график растягивается на всю доступную ему ширину и правилу подбора появляются дополнительные деления
![image](https://user-images.githubusercontent.com/75831445/108975022-19cdf780-7697-11eb-9985-c8227049a43a.png)

Но когда я его включаю, график начинает искусственно растягиваться. На скрине справа реальные данные есть в точках 1 и 2, а все остальное — просто соединение, ему не нужно столько внимания
![image](https://user-images.githubusercontent.com/75831445/108975103-2ce0c780-7697-11eb-99a8-2c1d253ea005.png)

Отсюда
- [ ] сделать, чтобы при ограниченной ширине шага не появлялись избыточные направляющие, растягивающие график

2021-02-25 11:33 UTC, schurf-des commented
И еще один момент, согласуйте плиз нейминг всего, что торчит наружу, с командой, которая делает барчарт
- [ ] название одинаковых параметров у лайнчарта и барчарта должно быть одинаковым

2021-02-26 16:50 UTC, karpovfv-nedra commented
> > Большинство правок по замечениям из пулл реквеста #3 сделал.
> > Добавил ещё функцию `onItemClick` для легенд айтемов, подумал что возможно пригодится на будущее. Всем функциям мыши (onMouseEnter, onMouseLeave, onClick) прокинул событие мыши ещё.
> > В `LineTooltip.tsx ` там уже используется в свойствах, это дефолтные подписи на случай, если пользователь не укажет ничего
> > > давай эти слова вынесем в свойства компонента
> > 
> > 
> > ========================================
> > Остались вопросы по некоторым пунктам:
> > 
> > 1. Мы сейчас оставляем в `LegendItem` только отображение точки (dot) и возможность самому прокидывать иконку через `renderLeftSide: () => ReactNode` ? Линию тоже убираем? Не понял в итоге что мы оставляем, а что убираем..
> > 2. Не понял момент в `LegendItem.tsx` про:
> > 
> > > давай задавать ccs переменную --icon-color у рутового компонента
> > > и в css уже куда надо туда ее и прокидывать
> > 
> > 
> > 
> > 1. Я бы создал отдельной задачей переписать функции из `lodash` на свои в utils, так как этих функций немало используется в коде линеар и бар чартов, и других необходимых компонентах.
> 
> 1. линию и точку оставьте, renderLeftSide на случай если потребуется передать что-то  свое
> 2. суть в том чтобы передавать в `style={{'--color-icon': color}}` и в css уже эту переменную использовать в одном случае как `background`, в другом как `color`
> 3. давай

Сделано.
задачу по лодашу создал: https://github.com/gazprom-neft/consta-widgets-new/issues/23

2021-02-26 16:51 UTC, karpovfv-nedra commented
> Привет, по дизайну было бы хорошо поправить пару моментов.
> 
> #### Оформление всех чисел
> * [ ]  Запятые вместо точек в дробях
> * [ ]  Минусы вместо дефисов
> * [ ]  От четырех знаков должен быть пробел
> * [ ]  Числа не переводятся в экспоненциальную форму
> * [ ]  у подписей шкалы всегда одинаковая разрядность. Если хотя бы у одного значения шкалы есть дробная часть, точно такая же есть у остальных.
> 
> см. https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=2202%3A4014
> 
> #### Тултип
> * [ ]  инвертировать тему тултипа. дефолт для дисплея и дарка, дарк для дефолта
> * [ ]  Предел отображается в тултипе без шарика с цветом
> * [ ]  зона ховера должна быть больше, чем линия или точка. 50% от величины шага.
> 
> #### Прочее оформительство
> * [*]  размер точек, r=2.5 → 3
> * [ ]  расстояние от сетки до нижней шкалы xs (8)
> * [ ]  расстояние от сетки до боковой шкалы xs
> * [ ]  если есть куда скроллить, с нужной стороны должна быть тень
>   https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=295%3A4
> * [ ]  Если линия расходится от нуля, сейчас рисуется один общий градиент, нужно два разных
>   https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=1599%3A59
> 
> #### limitMinimumStepSize и шкала
> Когда limitMinimumStepSize отключен, логично, что график растягивается на всю доступную ему ширину и правилу подбора появляются дополнительные деления
> ![image](https://user-images.githubusercontent.com/75831445/108975022-19cdf780-7697-11eb-9985-c8227049a43a.png)
> 
> Но когда я его включаю, график начинает искусственно растягиваться. На скрине справа реальные данные есть в точках 1 и 2, а все остальное — просто соединение, ему не нужно столько внимания
> ![image](https://user-images.githubusercontent.com/75831445/108975103-2ce0c780-7697-11eb-99a8-2c1d253ea005.png)
> 
> Отсюда
> 
> * [ ]  сделать, чтобы при ограниченной ширине шага не появлялись избыточные направляющие, растягивающие график

2021-03-01 08:47 UTC, gizeasy requested changes

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +            <IconWarning className={cnLegendItem('Sign', { icon })} size="s" style={{ color }} />
давай задавать ccs переменную --icon-color у рутового элемента
и в css уже куда надо туда ее и прокидывать

```tsx
<div className={cnLegendItem({ size }, [className])}  style={{...style, ['--icon-color ' as string]: color}} >
```

2021-03-01 08:47 UTC, gizeasy commented on src/Legend/Legend.tsx
> +          // style={{ ['--icon-color' as string]: getItemColor(item) }}
тут просто передавать `color` а в нутри компонета уже на рут-див повешать style

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  const dotStyle = icon === 'dot' ? { width: DOT_SIZE, height: DOT_SIZE } : {}
`{ width: DOT_SIZE, height: DOT_SIZE }` - давай приберем в css

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +            <IconWarning className={cnLegendItem('Sign', { icon })} size="s" style={{ color }} />
@schurf-des какой цвет применять если цвет не пришел.

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +            <IconWarning className={cnLegendItem('Sign', { icon })} size="s" style={{ color }} />
`IconWarning` удалить из компонента, оставить возможность рендерить любой копонент в качестве иконки   
чтото вроде renderLeftSide

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +type CommonProps = {
запрети прокидывать children 
`children?: never`

2021-03-01 08:47 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +        ['--dot-size' as string]: `${DOT_SIZE}px`,
а зачем нам из JS задавать размер кружечка. Думаю можно просту указать в css

2021-03-01 08:47 UTC, gizeasy commented on src/Legend/Legend.tsx
> +          renderLeftSide={renderLeftSide}
Поговорили по поводу апи иконок и есть изменения. Извини что не сразу((
давай оставим 1 пропс icon `'dot', 'line', 'lineBold', 'gap', React.FC<IconProps>`
gap - отступ на размер иконки
React.FC<IconProps> - компонент иконки нашего формата, взять IconProps можешь из @consta/uikit/Icon

внутри если строка то применяешь модификатор если функция то рисуешь иконку.

2021-03-01 09:14 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +            <IconWarning className={cnLegendItem('Sign', { icon })} size="s" style={{ color }} />
эти пункты уже сделаны, спасибо)

2021-03-01 09:14 UTC, karpovfv-nedra commented on src/Legend/Legend.tsx
> +          // style={{ ['--icon-color' as string]: getItemColor(item) }}
ага, сделано

2021-03-01 09:14 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +  const dotStyle = icon === 'dot' ? { width: DOT_SIZE, height: DOT_SIZE } : {}
перенесу

2021-03-01 09:15 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +        ['--dot-size' as string]: `${DOT_SIZE}px`,
я указал в js его, чтоб потом можно было использовать этот размер в качестве паддинга у айтема в тултипе. я перенесу в css это, так как появится новое свойство `gap`

2021-03-01 11:11 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +  const dotStyle = icon === 'dot' ? { width: DOT_SIZE, height: DOT_SIZE } : {}
отправил в css

2021-03-01 11:11 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +type CommonProps = {
сделано

2021-03-01 11:11 UTC, karpovfv-nedra commented on src/Legend/Legend.tsx
> +          renderLeftSide={renderLeftSide}
сделано

2021-03-01 11:11 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +        ['--dot-size' as string]: `${DOT_SIZE}px`,
в css перенёс

2021-03-02 17:22 UTC, schurf-des commented
- [ ] Что-то не так с осями, ось Y отображает не те значения, что на ней реально отражены
![image](https://user-images.githubusercontent.com/75831445/109682663-ad1f9500-7b8f-11eb-9806-9c683d516033.png)

- [ ] Тень при скролле пусть использует --color-bg-secondary
- [ ] Сдвиг тени по Х на 20
- [ ] Внутреннюю светлую тень можно убрать, из макетов вычищу, с ней грязновато
- [ ] Бокс, отбрасывающий тень, должен доходить покрывать и скроллбар

- [ ] В продолжение с limitMinimumSize: если он включен, но точек мало и они с учетом минимального размера могут уместиться без скролла, скролл не должен появляться. Сейчас появляется.

- [ ] крайние подписи давайте тоже выравнивать по центру относительно их направляющих. 
![image](https://user-images.githubusercontent.com/75831445/109687945-cbd45a80-7b94-11eb-96b5-287b3c27f085.png)
Как сделано сейчас конечно симпатичней, но велик риск, что так крайние значения будут налезать на соседей, если они большие

- [ ] И согласуйте, пожалуйста, названия параметров с командой барчарта. Сейчас в барчарте, например, подпись оси зовется unit, в лайнчарте — yDimensionUnit. Это одно и то же, пусть называется одинаково. И так со всеми остальными.

2021-03-04 13:42 UTC, karpovfv-nedra commented
> * [x ]  Что-то не так с осями, ось Y отображает не те значения, что на ней реально отражены
>   ![image](https://user-images.githubusercontent.com/75831445/109682663-ad1f9500-7b8f-11eb-9806-9c683d516033.png)
> * [x ]  Тень при скролле пусть использует --color-bg-secondary
> * [x ]  Сдвиг тени по Х на 20
> * [x ]  Внутреннюю светлую тень можно убрать, из макетов вычищу, с ней грязновато
> * [ x]  Бокс, отбрасывающий тень, должен доходить покрывать и скроллбар
> * [x ]  В продолжение с limitMinimumSize: если он включен, но точек мало и они с учетом минимального размера могут уместиться без скролла, скролл не должен появляться. Сейчас появляется.
> * [ x]  крайние подписи давайте тоже выравнивать по центру относительно их направляющих.
>   ![image](https://user-images.githubusercontent.com/75831445/109687945-cbd45a80-7b94-11eb-96b5-287b3c27f085.png)
>   Как сделано сейчас конечно симпатичней, но велик риск, что так крайние значения будут налезать на соседей, если они большие
> * [ x]  И согласуйте, пожалуйста, названия параметров с командой барчарта. Сейчас в барчарте, например, подпись оси зовется unit, в лайнчарте — yDimensionUnit. Это одно и то же, пусть называется одинаково. И так со всеми остальными.

В качестве тени использовал градиент с начальным значением `rgba(var(--color-nums-shadow), 0.5)` .
Крайние подписи везде выравниваются сейчас по центру, за исключением случая, когда у нас появляется скролл - из-за особенности реализации, так как половинки значений будут спрятаны за пределы контейнера.

2021-03-05 10:02 UTC, gizeasy requested changes

2021-03-05 10:02 UTC, gizeasy commented on src/LegendItem/LegendItem.stories.tsx
> +const getCommonProps = () =>
Здесь ты сам определяещь пропсы, а нижеиспользуешь декоратор `withSmartKnobs`
нужно либо убрать ручное добавление кнобов либо оставить автоматическое.

если будешь делать ручное добавь в `getCommonProps` `label`

и еще давай расширим кноб icon, пунктом `customIcon` и в примере будешь уже добавлять иконку, тогда можно будет убрать вторую стори

2021-03-05 10:02 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +            <div className={cnLegendItem('Sign')}>
думаю возможно избежать лишней вложенности
```tsx 
<Icon className={cnLegendItem('Sign')} />
```

2021-03-05 11:24 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.tsx
> +            <div className={cnLegendItem('Sign')}>
от вложенности избавился

2021-03-05 11:26 UTC, karpovfv-nedra commented on src/LegendItem/LegendItem.stories.tsx
> +const getCommonProps = () =>
оставил ручное добавление, добавил ещё `label`, а вот как нормально добавить customIcon в список кнобов icon пока не раскурил

2021-03-05 14:31 UTC, schurf-des approved these changes

2021-03-09 07:44 UTC, gizeasy approved these changes

2021-03-10 12:46 UTC, gizeasy commented
конфликты

2021-03-10 15:06 UTC, karpovfv-nedra commented
> конфликты

разрезолвил

2021-03-10 16:26 UTC, merged