feat(components): добавлена возможность расчитывать минимальный размер DonutChart на основе контента
consta-design-system/widgets pull request #20
Opened 2021-02-25 07:47 UTC by al-fyodorov

## Описание изменений

* упрощен компонент CoreDonutChartPie;
* упрощен компонент CoreDonutChart;
* генерация и предрасчет размеров вынесены в отдельные хелперы;
* добавлены тесты на хелперы;
* с учетом переноса расчетов в сам CoreDonutChart теперь можно считать размер подписей к дугам и прибавлять к минимальному размеру пончика что будет довольно удобно при дальнейшей разработке;

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-26 11:30 UTC, al-fyodorov commented
@schurf-des, на стендах можно проверить теории про минимальный размер и необходимость ограничений для безтекстовых пончиков.

2021-03-01 08:12 UTC, gizeasy commented
@al-fyodorov как это можно проверить? я пробовал убирать ширину и высоту, в итоге график исчезает

2021-03-01 08:20 UTC, al-fyodorov commented
@gizeasy дело как раз в том что просили совсем убрать ограничение на минимальную ширину и высоту кроме одного случая, когда отображается текст в центре на одном кольце.

@schurf-des хотел посмотреть как будет выглядеть на стенде такое поведение.

2021-03-01 14:39 UTC, gizeasy commented
@schurf-des все хорошо?

2021-03-01 18:46 UTC, typeetfunc requested changes

2021-03-01 18:46 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/__tests__/helpers.test.ts
> +  it('', () => {
?

2021-03-02 10:07 UTC, gizeasy approved these changes

2021-03-02 12:27 UTC, schurf-des commented
Из слака: 
> Поглядел. Давай минимальный размер тогда у бестекстовых тоже, меньше там какой-то треш в плане прицеливания начинается, пользы в этом кажется не будет, не будем усложнять условиями. А то щас там вроде ограничения у полупончиков нет, а вот полноценный не уменьшается.

> Итого — у всех круглых 100х100 минимум, у всех полуколец 100х50. Независимо, есть текст или нет

2021-03-03 13:24 UTC, al-fyodorov commented
Тесты упали несколько раз потому что перед тестированием подливается master ветка если конфликтов нет, конфликтов не было, но в master у `<DonutChart />` появился файл `helpers.ts` в котором используются типы замененные в текущем PR, из-за этого была ошибка что тип не существует, локально не смог выявить пока master не подлил.

2021-03-03 13:25 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/__tests__/helpers.test.ts
> +  it('', () => {
Исправил.

2021-03-03 13:26 UTC, al-fyodorov commented
@schurf-des, добави ограничения в соответствии с требованиями.

2021-03-05 07:41 UTC, schurf-des commented
Если взять донат и поставить туда тайтл, например, одну цифру, он будет выглядеть вот так
![image](https://user-images.githubusercontent.com/75831445/110083051-3d7ff480-7d9f-11eb-8597-40a16c577a84.png)

А потом можно подвинуть границу браузера и он перерисуется в нормальный размер
![image](https://user-images.githubusercontent.com/75831445/110083101-512b5b00-7d9f-11eb-9d9e-dcad58ce4eef.png)

Можем сделать так, чтобы без двигания это срабатывало в сторибуке?

2021-03-05 07:44 UTC, schurf-des approved these changes

2021-03-05 13:47 UTC, merged