fix(components): исправлено отображение текста в виджете CoreDonutChart
consta-design-system/widgets pull request #22
Opened 2021-02-26 07:53 UTC by al-fyodorov

## Описание изменений

* изменены условия отрисовки;
* изменены расчета размера основного и второстепенного текста;

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-01 08:19 UTC, gizeasy approved these changes

2021-03-01 18:27 UTC, typeetfunc requested changes

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +    ratio: value ? 0.4 : 1,
давай использовать LABEL_MAX_HEIGHT_RATIO ?

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/helpers.ts
> +export const getHeightPaddingRatio = (half: HalfDonutDirection) => {
либо сгенерировать эти функции через фабрику либо убрать в константы значения

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +    ratio: label ? 0.6 : 1,
VALUE_MAX_HEIGHT_RATIO ?

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +  const textPadding = half === 'horizontal' ? heightPadding : heightPadding * 2
это getContentHeight({ radius: heightPadding, half }) ?

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +  const textPadding = half === 'horizontal' ? heightPadding : heightPadding * 2
ну или можно алиас сделать
иначе получается разнородность

2021-03-01 18:27 UTC, typeetfunc commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/helpers.ts
> +export const getDonutHalfDirection = (half?: HalfDonut) => {
в одних функциях half это HalfDonut а в других HalfDonutDirection
давай поименуем более однородно

2021-03-02 12:57 UTC, schurf-des commented
Давайте сделаем label 2/3 от фактического размера value. Иначе получаются вот такие штуки, не круто
![image](https://user-images.githubusercontent.com/75831445/109651708-ef38de80-7b6f-11eb-876f-482de67100ba.png)

2021-03-02 15:47 UTC, schurf-des commented
И давайте текст в центре приведем к такому виду.
https://www.figma.com/file/wiufHxMKmLnOm0dEWT6lfO/widgets-2.0?node-id=2202%3A4014

Если вкратце:
- [ ] вместо точек дробная часть отделяется запятыми
- [ ] каждые три символа, отсчитывая от запятой, отделяются пробелом

2021-03-04 06:56 UTC, al-fyodorov commented
@typeetfunc посмотри изменения уже после влития, может будут еще какие замечания. По поводу замечаний от дизайнера, то учел все требования.

2021-03-04 07:10 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +    ratio: value ? 0.4 : 1,
Исправил.

2021-03-04 07:11 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/helpers.ts
> +export const getHeightPaddingRatio = (half: HalfDonutDirection) => {
Исправил.

2021-03-04 07:11 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +    ratio: label ? 0.6 : 1,
Исправил.

2021-03-04 07:11 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/CoreDonutChartText.tsx
> +  const textPadding = half === 'horizontal' ? heightPadding : heightPadding * 2
Исправил.

2021-03-04 07:11 UTC, al-fyodorov commented on src/__private__/components/CoreDonutChart/CoreDonutChartText/helpers.ts
> +export const getDonutHalfDirection = (half?: HalfDonut) => {
Исправил.

2021-03-04 07:18 UTC, merged