docs(commits-style): заменены примеры на актуальные
consta-design-system/widgets pull request #27
Opened 2021-03-03 08:54 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-03 11:19 UTC, arhayka requested changes

2021-03-03 11:19 UTC, arhayka commented on docs/developers/commits-style.mdx
> +    # имена компоненторв
компонентов (опечатка сейчас, лишнее компоненто**р**в)

2021-03-03 11:29 UTC, al-fyodorov requested changes
Кажется нужно доработать конфигурацию commitizen, чтобы убрать от туда скоуп components или описать зачем он нужен и в каких случаях применять.

2021-03-09 07:18 UTC, gizeasy commented
> Кажется нужно доработать конфигурацию commitizen, чтобы убрать от туда скоуп components или описать зачем он нужен и в каких случаях применять.

в отдельном комите

2021-03-09 07:20 UTC, arhayka approved these changes

2021-03-09 09:46 UTC, al-fyodorov approved these changes

2021-03-10 16:27 UTC, merged