docs(linear chart): update docs
consta-design-system/widgets pull request #28
Opened 2021-03-08 05:49 UTC by arhayka

## Описание изменений

1. Отредактировала доку и описала то, что было не описано.
2. Поменяла местами разделы (кажется, так логичнее, сделаю так везде).
3. Добавила примеры, где смогла.

Не получилось добавить пример легенды, пример со скрытой подписью к первому делению и что-то еще не получилось. Можно выложить так, но если будет возможность, лучше добавить примеры на каждое дадже самое маленькое свойство: словами графические штуки описываются плохо, а открывать соседнюю вкладку и искать, правильно ли ты понял слова, неудобно.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-09 07:41 UTC, gizeasy approved these changes

2021-03-09 20:16 UTC, schurf-des requested changes

2021-03-09 20:16 UTC, schurf-des commented on src/LinearChart/__stories__/LinearChart.mdx
> +Чтобы показать на графике пропуск (не показывать линию между двумя точками), укажите координаты точек, а между ними в промежуточных значениях добавьте `null`.
Раньше работало так — не ставишь точки в конце или начале, он не рисует там линию. Не ставишь точки в середине — он соединяет пунктиром соседние. Сейчас это убрали, правило проще — если отправить нулл, линия прервется в этом месте, точка не нарисуется. И эти два абзаца выглядят странно, будто про одно и то же написали два раза зачем-то.

2021-03-09 20:16 UTC, schurf-des commented on src/LinearChart/__stories__/LinearChart.mdx
> +- показать ось координакт (саму линию): `showGuide`,
Здесь важный момент — он рисует сплошным именно оси Ох и Оу. Если график настроен так, что ноль на шкале не видно, и осей тоже не будет

2021-03-09 20:16 UTC, schurf-des commented on src/LinearChart/__stories__/LinearChart.mdx
> +- зафиксировать минимальный размер шага между делениями:`limitMinimumStepSize` (шаг уменьшится до 30 пикселей и меньше становиться не будет),
По дефолту параметр отключен и график уместит все данные на доступную площадь. Если включить, может появиться скролл, если данных много

2021-03-09 20:16 UTC, schurf-des commented on src/LinearChart/__stories__/LinearChart.mdx
> +- нарисовать сетку, которая не будет зависеть от самого графика, с помощью `min` и `max`. В `min` указываете значение первого деления на соответствующей оси, в `max` — последнее.
Кажется, тут корректней говорить про минимум и максимум на шкале, и можно дать пример ситуации. Например, если важно строить именно от нуля чтобы показать масштаб, ставьте в минимум 0.

2021-03-09 20:16 UTC, schurf-des commented on src/LinearChart/__stories__/LinearChart.mdx
> +Чтобы убрать подпись к первому делению по оси абсцисс, добавьте `xHideFirstLabel`.
Может быть полезно, если обе оси строятся от нуля. Тогда, чтобы его не дублировать, одно значение можно скрыть

2021-03-18 18:13 UTC, arhayka commented on src/LinearChart/__stories__/LinearChart.mdx
> +Чтобы показать на графике пропуск (не показывать линию между двумя точками), укажите координаты точек, а между ними в промежуточных значениях добавьте `null`.
Да, че-то намудрила тут)

2021-03-18 18:34 UTC, arhayka commented
Посмотрела все правки, внесла изменения. Гляньте, плиз.

2021-03-22 15:28 UTC, kolebayev approved these changes

2021-04-13 14:11 UTC, merged