docs(BarChart): edit docs
consta-design-system/widgets pull request #29
Opened 2021-03-08 10:19 UTC by arhayka

## Описание изменений

Поправила доку, не очень много меняла: и так было неплохо.
1) Поменяла местами разделы (кажется, так лучше, везде так сделаю).
2) Добавила то, что не было описано.

Вопросы:

1) Если происходит переполнение, то столбец, который не влез на диаграмму, будет подписываться.

В примере ничего не происходит. Расскажите, что это значит, где должна появиться подпись?

2) limitMinimumCategorySize — что это такое, минимальный шаг между чем и чем? Сейчас максимально расплывчатое описание.

3) Ширина столбцов или группы зависит от соотношения — от соотношения чего?)

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-09 07:33 UTC, gizeasy approved these changes

2021-03-09 20:36 UTC, schurf-des requested changes

2021-03-09 20:36 UTC, schurf-des commented on src/BarChart/__stories__/BarChart.mdx
> +Если цвет не указан или с ним что-то не так, столбик покрасится в системный цвет (`--color-bg-system`).
ghost

2021-03-09 20:36 UTC, schurf-des commented on src/BarChart/__stories__/BarChart.mdx
> +посередине диаграммы.
Не обязательно. Шкала все равно подбирается так, чтобы вместить все и максимально задействовать площадь. Т.е. если будет куча больших положительных и маленькие отрицательные значения, ось будет смещена в нужную сторону, так чтобы не было кучи пустого пространства.

2021-03-09 20:36 UTC, schurf-des commented on src/BarChart/__stories__/BarChart.mdx
> +Если происходит переполнение, то столбец, который не влез на диаграмму, будет подписываться.
Кажется, это надо написать где-то после ручного указания максимума и минимума. Потому что переполнение происходит из-за них

2021-03-09 20:36 UTC, schurf-des commented on src/BarChart/__stories__/BarChart.mdx
> +Максимальная ширина столбика в группе — 70% от ширины группы.
Кажется, такая точность в доке ни к чему — можно просто обговорить, что ширина столбиков подбирается автоматически в зависимости от фактического размера графика и количества столбиков на нем. Если будем менять процент, не придется править тут

2021-03-09 20:36 UTC, schurf-des commented on src/BarChart/__stories__/BarChart.mdx
> +- за нулевую линию — `showLineAtZero`. Если скрыта нулевая линия, то сетка отображаться не будет.
Они должны были в последнем ПР поменять названия пропсов, чтобы те совпадали с лайнчартом

2021-03-14 16:53 UTC, arhayka commented on src/BarChart/__stories__/BarChart.mdx
> +посередине диаграммы.
ну я тут хотела сказать, что ось — это ноль)) а не край диаграммы. возможно, это и так понятно. поменяла это

2021-03-14 17:04 UTC, arhayka commented on src/BarChart/__stories__/BarChart.mdx
> +Максимальная ширина столбика в группе — 70% от ширины группы.
Огонь, так и напишем)

2021-03-15 07:22 UTC, arhayka commented on src/BarChart/__stories__/BarChart.mdx
> +- за нулевую линию — `showLineAtZero`. Если скрыта нулевая линия, то сетка отображаться не будет.
подтянула мастер, поменяла то, что поменялось.

2021-03-15 07:24 UTC, arhayka commented
Так. Я подтянула мастер, поменяла то, что поменялось. При этом добавилось свойство `gridTicks` — оно точно нужно? Нигде в коде его не увидела.

@gizeasy @schurf-des  Посмотрите, плиз.

2021-03-22 15:29 UTC, kolebayev approved these changes

2021-04-13 14:26 UTC, merged