feat(LinearChart): added linear chart
consta-design-system/widgets pull request #3
Opened 2021-02-11 20:51 UTC by karpovfv-nedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-12 10:39 UTC, gizeasy commented
тесты не прошли

2021-02-12 10:45 UTC, gizeasy requested changes

2021-02-12 10:45 UTC, gizeasy commented on .storybook/main.js
> +    // const projectConfig = flowRight([withMdxRules, disableCSSModules])(
нужно оставить `disableCSSModules `

2021-02-12 10:45 UTC, gizeasy commented on src/Legend/index.css
> +.main {
приведите к структуре
на проекте следует именовать классы по БЭМ
https://consta-widgets.consta.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page

2021-02-12 10:45 UTC, gizeasy commented on src/Legend/index.tsx
> +import css from './index.css'
не используем css-modules

2021-02-16 08:27 UTC, karpovfv-nedra commented on src/Legend/index.tsx
> +import css from './index.css'
переделал на бэм

2021-02-16 08:28 UTC, karpovfv-nedra commented on .storybook/main.js
> +    // const projectConfig = flowRight([withMdxRules, disableCSSModules])(
вернул дизейблинг цсс модулей

2021-02-16 14:11 UTC, gizeasy requested changes
Я еще не досмотрел, завтра закончу смотреть

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +// const sizeClass = {
кажется что забыл убрать комментарий

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +type Props = {
Добавь все свойства рутового JSX элемента

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +      className={cnLegendItem('Main', { fontSize, position: positionClass }, [className])}
Добавь все свойства рутового JSX элемента и разверни тут

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +export const LegendItem: React.FC<Props> = ({
оберни в forwardRef, думаю что лишним не будет

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  fontSize = 's',
лучше переименовать на `size`

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  lineBold,
логичнее будет добавить `lineBold` в модификатор `type` и убрать это свойство

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.css
> +    &_isBold {
убрать и добавить новое значение модификатора `type`

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.css
> +  &-Text {
у компонента  Text есть свойство `display="inlineBlock"`

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  const dotStyle = type === 'dot' ? { width: DOT_SIZE, height: DOT_SIZE } : {}
Обсудили в команде этот момент, решили точку оставить такой какая она есть, но в компоненте сделать возможность проброса своего компонента в место иконки.

`renderLeftSide: () => ReactNode`

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +              className={cnLegendItem('Sign', { type_icon: true })}
`{ type: 'icon' }`

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +              style={{ color }}
давай задавать ccs переменную `--icon-color` у рутового компонента
и в css уже куда надо туда ее и прокидывать

2021-02-16 14:11 UTC, gizeasy commented on src/Legend/Legend.tsx
> +  data: Data
давай переименуем в items

2021-02-16 14:11 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +              size={fontSize}
оставь иконку всегда размером S

2021-02-16 14:11 UTC, gizeasy commented on src/Legend/Legend.tsx
> +export type Item = {
думаю лучше будет не задавать конкретный тип Item
а сделать его дженериком, чтоб пользователям не приходилось форматировать свои данные при пробросе в компонент. А доставать text, color и прочие свойста item, сделать геттеры которые должны будут уже возвращать определенный тип.

`getItemLabel: (item) => string`

2021-02-16 14:11 UTC, gizeasy commented on src/Legend/Legend.tsx
> +  onItemMouseEnter?: (item: Item) => void
`({item: Item, e: MouseEvent}) => void` - думаю полезно будет прокидывать событие клика.

2021-02-17 10:15 UTC, gizeasy requested changes

2021-02-17 10:15 UTC, gizeasy commented on src/Legend/Legend.tsx
> +  labelType: LabelType
переименовать на`type`

2021-02-17 10:15 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +      className={cnLegendItem('Main', { fontSize, position: positionClass }, [className])}
ОБычно название рутового блока совпадает с названием компонента, 
`cnLegendItem('Main', { fontSize, position: positionClass }, [className])` -> `cnLegendItem(null, { fontSize, position: positionClass }, [className])`

2021-02-17 10:15 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  const positionClass = ['dot', 'warning'].includes(type) ? 'left' : position
@schurf-des 

свойство position, изменяет позицию иконки - либо сверху либо с лева, но работает это все только если выбран type="line. 
Нужны ли эти ограничения?

2021-02-17 10:15 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  type?: LabelType
тип влияет только на отображдение иконки.
Давай переименуем в icon.

2021-02-17 10:15 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  children,
@schurf-des в качестве текста можно использовать любую верстку или только текст?

2021-02-17 10:15 UTC, gizeasy commented on src/LinearChart/LinearChart.tsx
> +            {/*    <rect width={svgWidth} height={svgHeight} />*/}
забыли убрать

2021-02-17 10:15 UTC, gizeasy commented on src/LinearChart/LinearChart.tsx
> +import { HoverDots } from '@/LinearChart/components/HoverDots/HoverDots'
папку components убрать

2021-02-17 10:15 UTC, gizeasy commented on src/LinearChart/components/LineTooltip/LineTooltip.tsx
> +          ? `${idx === 0 ? 'Верхнее' : 'Нижнее'} пороговое значение`
давай эти слова вынесем в свойства компонента

2021-02-17 10:15 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  position?: LabelPosition
@schurf-des говорит что можно вообще выпилить `position` эта модификация больше не нужна

2021-02-17 10:15 UTC, gizeasy commented on src/LinearChart/components/Frame/Frame.css
> +    & > .domain {
Возможно ли эти классы переделать по БЭМ?

2021-02-17 10:15 UTC, gizeasy commented on src/LinearChart/LinearChart.tsx
> +import * as _ from 'lodash'
не хочется чтоб в библиотеке была зависимость  `lodash`, если в utils описать необходимые функции по работе с массивами и объектами то думаю также удобно будет работать + лишней зависимости не будет

2021-02-18 16:02 UTC, gizeasy commented on src/Legend/Legend.tsx
> +export type Item = {
тут к обсуждению, возможно что для виджетов это будет излишнее

2021-02-18 16:05 UTC, gizeasy commented on src/LegendItem/LegendItem.tsx
> +  children,
только текст, думаю по этому убрать children и добавить свойство label

2021-02-18 16:09 UTC, gizeasy commented
нам нужно влить этот пр без полного отсмотра,
@al-fyodorov посмотри его все равно, все замечания поправят в рамках
https://github.com/gazprom-neft/consta-uikit/issues/875

2021-02-18 16:32 UTC, merged

2021-02-19 09:01 UTC, al-fyodorov commented
@gizeasy, сначала перенос с переводом на БЭМ. А потом уже правки API. Декомпозируйте свои задачи, так как сейчас в рамках одного PR вы чуть-ли не все и сразу хотите, а это:

1. большой PR трудно ревьюить;
2. большое количество конфликтов если переносятся сразу несколько виджетов;
3. так как виджеты довольно объемные, то легко что-то сломать и не заметить этого, а ревьюер этого не увидит из-за пункта 1.