docs(DonutChart): edit docs
consta-design-system/widgets pull request #30
Opened 2021-03-08 12:15 UTC by arhayka

## Описание изменений

Дописала про легенду, максимальные значения и сортировку. Про сортировку не оч. поняла, что и как сортируется. Расскажите, плиз.

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-03-09 07:19 UTC, gizeasy approved these changes

2021-03-09 07:22 UTC, gizeasy requested changes

2021-03-09 07:22 UTC, gizeasy commented on src/DonutChart/__stories__/DonutChart.mdx
> +    - [Максимальные значения](#максимальные значения)
ссылка не рабочая, пропустила `-`
`#максимальные-значения`

2021-03-09 20:39 UTC, schurf-des requested changes

2021-03-09 20:39 UTC, schurf-des commented on src/DonutChart/__stories__/DonutChart.mdx
> +Вы отсортировать значения с помощью `'sortValue'`. По умолчанию они сортируются от меньшего к большему.
Можно отсортировать от большого к меньшему, отсчет от "12 часов". А можно показать в том порядке, в котором пришли

2021-03-10 07:00 UTC, arhayka commented on src/DonutChart/__stories__/DonutChart.mdx
> +Вы отсортировать значения с помощью `'sortValue'`. По умолчанию они сортируются от меньшего к большему.
Спасибо! А можно пример — как это сделать?) Я тут не очень поняла.

2021-03-14 16:44 UTC, arhayka commented on src/DonutChart/__stories__/DonutChart.mdx
> +Вы отсортировать значения с помощью `'sortValue'`. По умолчанию они сортируются от меньшего к большему.
> Можно отсортировать от большого к меньшему, отсчет от "12 часов". А можно показать в том порядке, в котором пришли

Спасибо, я это добавила, но не разобралась, как отсортировать в обратном порядке. Было бы круто добавить пример, но если вы считаете, что и так понятно, можно без него.

2021-03-16 15:17 UTC, schurf-des approved these changes

2021-04-13 14:37 UTC, merged