Feat bar chart
consta-design-system/widgets pull request #4
Opened 2021-02-12 08:23 UTC by yekaterinadochinetsnedra

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-18 10:59 UTC, gizeasy requested changes

2021-02-18 10:59 UTC, gizeasy commented on src/BarChart/index.tsx
> +import React from 'react'
переименуй файл в название Блока
а в index.ts сделай реэкспорт компонента

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/helpers.ts
> +        withBottomTicksRow &&
Нужно классы написать по БЭМ
Можно создать Блок BarChartGrid и с помощью него описать классы

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/BarChart.tsx
> +      className={axisTicksPositionsClasses[position]}
Стоит выразить через блок `Ticks` или `AxisTicks` c модификатором `position `

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/BarChart.css
> +  &-topTicks,
Не нужно плодить кучу элементов, можно создать 1 элемент и использовать модификаторы

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/BarChart.tsx
> +import React, { useLayoutEffect, useRef, useState } from 'react'
папку `components` убрать 
https://consta-widgets.consta.vercel.app/?path=/docs/%D1%81ommon-file-structure-components--page

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/components/Column/Column.css
> +    &_horizontal_isHorizontal {
очень странное названи е модификатора
проще сделать `_horizontal`

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/BarChart.tsx
> +import React, { useLayoutEffect, useRef, useState } from 'react'
компонент переименовать в CoreBarChart

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/components/Section/Section.css
> +    &_horizontal_isHorizontal {
опять странное название модификатора

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/components/Column/Column.css
> +    &_reversed {
думаю лучше оставить 2 модификатора _reverse и _horizontal и уже стилями разрулить

или сделать модификатор direction со значениями  horizontal, vertical, horizontalReverse, verticalReverse

2021-02-18 10:59 UTC, gizeasy commented on src/__private__/components/BarChart/components/Threshold/Threshold.css
> +    &_horizontal_isHorizontal {
тоже исправить название модификатора

2021-02-18 15:48 UTC, gizeasy commented
нам нужно влить этот пр без полного отсмотра, 
@al-fyodorov посмотри его все равно, все замечания поправят в рамках 
https://github.com/gazprom-neft/consta-uikit/issues/874

2021-02-18 15:50 UTC, merged

2021-02-19 09:01 UTC, al-fyodorov commented
@gizeasy, сначала перенос с переводом на БЭМ. А потом уже правки API. Декомпозируйте свои задачи, так как сейчас в рамках одного PR вы чуть-ли не все и сразу хотите, а это:

1. большой PR трудно ревьюить;
2. большое количество конфликтов если переносятся сразу несколько виджетов;
3. так как виджеты довольно объемные, то легко что-то сломать и не заметить этого, а ревьюер этого не увидит из-за пункта 1.