feat(components): виджет Stats переведен на новое API
consta-design-system/widgets pull request #5
Opened 2021-02-15 08:28 UTC by al-fyodorov

BREAKING CHANGE:
В виджете больше не используются настройки `badge` и `numberBadge` для настройки отображения показателя
изменений.

## Описание задачи

Удалить старый API виджета и привести его в соответствии с требованиями заказчика из макета. Внешний вид включая отступы в этом PR не правились, в основном только API и добавление возможности вывода иконок.

## Чек-лист

- [x] PR: направлен в правильную ветку
- [x] PR: назначен исполнитель PR и указаны нужные лейблы
- [x] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [x] JS: нет варнингов и ошибок в консоли браузера
- [x] Тесты: новый функционал и исправленные баги покрыты тестами
- [x] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [x] Сторибук: для компонентов написаны или обновлены stories
- [x] Верстка: используются переменные из UI-kit
- [x] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-15 10:24 UTC, gizeasy requested changes

2021-02-15 10:24 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Давай оставим одну стори в кнобах укажем withTitleIcon.

2021-02-15 10:24 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Давай оставим одну story и в кнобах добавим withTitleIcon

2021-02-15 10:24 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +    iconTitle={<IconLighting width="100%" height="100%" />}
Давай лучше на вход принимать компонент иконки из конста, там на каждый размер иконки свое изображение, и нужно чтоб от размера компонента вставлялась иконка со своим размером и изображением для этого размера.

Лучше использовать иконки из ui-kit

Для добавления иконок в этот проект я добавлю шаблон формирования иконок, так чтоб при экспорте из svg появлялась иконка с типом как в конста.

2021-02-15 10:24 UTC, gizeasy commented on src/Stats/StatsIconArrowRate.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 40 30" fill="none"><path fill="currentColor" d="M20 0l20 31H0L20 0z"/></svg>
Может на css треугольник сделаем?

2021-02-15 10:24 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Также думаю отказаться от автоматических кнобов, в пользу "Ручных", чтобы абсолютно вся свойства компонента не тащились в кнобы, так как довольно частая история когда компонент по мимо своих своств имеет еще свойства JSX элемента, всякие `aria`, `onClick`, `id` и тд.

2021-02-15 11:27 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +    iconTitle={<IconLighting width="100%" height="100%" />}
Так сразу добавить не удалось сборку СВГ в проект. Давай на данном этапе будем использовать иконки только из ui-kit, если такой нет, то нужно добавить ее ui-kit.

2021-02-15 11:46 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Эм, раньше этого не обсуждалось, и в документации подобного требования не наблюдаю. Автоматические кнобы намного удобнее чем ручные если уметь ими пользоваться и скрывать не нужные как в текущем компоненте.

2021-02-15 11:50 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +    iconTitle={<IconLighting width="100%" height="100%" />}
А если пользователь хочет кастомную иконку под конкретный проект, и в UI-Kit такая иконка не нужна, то что делать будете? Например иконка отображающая тип скважины в Цубе или еще где.

2021-02-15 11:50 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Получается все же не одну, а две может быть? Обычная и с иконкой?

2021-02-15 11:51 UTC, al-fyodorov commented on src/Stats/StatsIconArrowRate.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 40 30" fill="none"><path fill="currentColor" d="M20 0l20 31H0L20 0z"/></svg>
Можно и на CSS, однако если иконка поменяется, то сейчас по сути только файл заменить вообще без правки чего либо еще.

2021-02-15 12:32 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
нам бы хотелось в идеале такую структуру: 1 компонент - 1 стори, и чтоб все возможные его модификации переключались с кнобов

2021-02-15 12:33 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
согласен, но довольно много исключений придется писать если компонент будет иметь свойства родительского JSX элемента

2021-02-15 12:35 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +    iconTitle={<IconLighting width="100%" height="100%" />}
сейчас у нас все компоненты используют могут использовать иконки определенного типа, и есть инструкция по созданию иконок для ДС как в дизайне так и в коде
https://consta-uikit.vercel.app/?path=/docs/components-icons--playground

2021-02-15 12:37 UTC, gizeasy commented on src/Stats/StatsIconArrowRate.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 40 30" fill="none"><path fill="currentColor" d="M20 0l20 31H0L20 0z"/></svg>
дизайнеры просят триугольник на CSS и думают что этот треугольник не поменяется. Если будет испотльзоваться другая иконка, то эту иконку добавят в ui-kit

2021-02-15 12:47 UTC, gizeasy commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
давай оставим авто-кнобы, в целом возможно собрать массив описывающий атирбуты JSX элемента которые стоит исключить.

2021-02-15 13:00 UTC, gizeasy requested changes

2021-02-15 13:00 UTC, gizeasy commented on src/Stats/Stats.tsx
> +  formatValue?: FormatValue
давай добавим все что умеет рутовый элемент компонента и развернем эти свойства в него

2021-02-15 13:00 UTC, gizeasy commented on src/Stats/Stats.tsx
> +    <div className={cnStats({ layout, size })}>
`cnStats({ layout, size },[className])`

и развернуть все своства которые умеет div

`<div {...otherProps}  className={cnStats({ layout, size },[className])}>`

таким образом пользователь сможет накинуть все что хочет на компонент, событие клика или любой html атрибут

2021-02-15 13:06 UTC, gizeasy requested changes

2021-02-15 13:06 UTC, gizeasy commented on src/Stats/Stats.tsx
>  export const Stats: React.FC<Props> = ({
давай еще обернем компонет в forwardRef и ссылку укажем на рутовый элемент компонента

2021-02-15 13:11 UTC, al-fyodorov commented on src/Stats/Stats.tsx
>  export const Stats: React.FC<Props> = ({
Добавь документацию когда по мнению UI-Kit надо добавлять forwardRef, а когда не стоит. Врядли он нужен везде.

2021-02-15 13:12 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +    <div className={cnStats({ layout, size })}>
Добавь в документацию требование к тому что все виджеты должны поддерживать такой проброс пропсов.

2021-02-15 13:12 UTC, al-fyodorov commented on src/Stats/StatsIconArrowRate.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 40 30" fill="none"><path fill="currentColor" d="M20 0l20 31H0L20 0z"/></svg>
Без проблем.

2021-02-15 13:13 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +    iconTitle={<IconLighting width="100%" height="100%" />}
1. Доки нет в дизайне статов;
2. Доки нет в этом репозитории;
3. Доки нет в коде этого репозитория.

Добавь ссылки на требования в документацию этого репозитория.

2021-02-15 13:14 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Собрать массив довольно легко, тем более что в большинтсве случчаев он будет почти что общий.

2021-02-15 13:15 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Ок, так как документации нет на то как должны у вас выглядеть нобы к компонентами и нобы с функциями добавлю как вижу.

2021-02-16 06:36 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +    <div className={cnStats({ layout, size })}>
Пока не вижу ни issue, ни PR, ни ветки на добавление документации.

2021-02-16 06:36 UTC, al-fyodorov commented on src/Stats/Stats.tsx
>  export const Stats: React.FC<Props> = ({
Пока не вижу ни issue, ни PR, ни ветки на добавление документации.

2021-02-16 06:53 UTC, gizeasy commented on src/Stats/Stats.tsx
>  export const Stats: React.FC<Props> = ({
https://github.com/gazprom-neft/consta-widgets-new/pull/6

2021-02-16 07:05 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +  formatValue?: FormatValue
Учитывай что место которое ты пометил и комментарий который ты оставил вводят немного в заблуждение. Кроме того после исправления твой комментарий не пометится исправленным, потому что оставил его в неправильном месте.

2021-02-16 07:07 UTC, al-fyodorov commented on src/Stats/StatsIconArrowRate.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 40 30" fill="none"><path fill="currentColor" d="M20 0l20 31H0L20 0z"/></svg>
Однако если есть какое-то обсуждение с дизайнерами, то стоит выносить такие вещи в макеты или требования, так как сейчас ничего из этого не было и догадаться что вы желаете треугольник на CSS из разряда чтения мыслей.

2021-02-16 07:10 UTC, al-fyodorov commented on src/Stats/__stories__/Stats.stories.tsx
> +export const WithIcon = createStory(() => (
Из-за добавления общей стори со всеми доступными нобами пока выпилил автонобы, чтобы указать выбор иконки и форматера по умолчанию.

2021-02-16 08:31 UTC, typeetfunc commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
> Если в value пустое значение — отображается прочерк 
а что с этим решили? Вадик вроде написал что это не правильно но как правильно не написал

2021-02-16 09:04 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
По поводу placeholder-а еще ведется обсуждение. Пока по макетам хотят чтобы виджет вообще не отображался если данных в `value` нет, что тоже немного странно.

2021-02-16 09:16 UTC, fooontic commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
@MariaLakomkina подключись, плиз

2021-02-16 09:30 UTC, gizeasy approved these changes

2021-02-16 09:30 UTC, gizeasy commented on src/Stats/StatsTitle/StatsTitle.tsx
> +      className={cnStatsTitle('', null, [className])}
`cnStatsTitle(null, [className])`

2021-02-16 09:31 UTC, gizeasy commented on src/Stats/StatsTitle/StatsTitle.tsx
> +      className={cnStatsTitle('', null, [className])}
исправь и вливай

2021-02-16 09:40 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
Уже на данный момент `value` обязательный параметр. Если в виджете нужен еще способ указывать `placeholder` если `value` всеже не пришел допустим `null`, то можно выводить его, это больше к формату предложения.

2021-02-16 09:47 UTC, typeetfunc commented on src/Stats/Stats.tsx
> +    status: !!rate ? undefined : status,
кстати про 0 в notion ничего нету, это еще раньше обсуждалось?

2021-02-16 09:50 UTC, typeetfunc approved these changes

2021-02-16 10:42 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +    status: !!rate ? undefined : status,
Там используется строка, поэтому эта проверка проблем не вызывает.

2021-02-16 11:38 UTC, MariaLakomkina commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
Решили, что value будет обязательный параметр для заполнения, т.е. по идее такого варианта, когда в value никаких значений не пришло — не должно быть. Но, если все-таки пустое значение, то на этот случай мы прописали в ноушене, что отображается прочерк.

2021-02-16 12:04 UTC, al-fyodorov commented on src/Stats/StatsTitle/StatsTitle.tsx
> +      className={cnStatsTitle('', null, [className])}
И еще в одном месте было, исправил.

2021-02-16 12:05 UTC, al-fyodorov commented on src/Stats/Stats.tsx
> +          {formatValue(value)}
Добавил еще пропс `placeholder` в котором можно этот прочерк задават, по умолчанию уже задан. Но если пользователю понадобится сможет исправить без доработок виджета.

2021-02-16 12:16 UTC, merged