docs(global): обновил документацю
consta-design-system/widgets pull request #6
Opened 2021-02-15 16:04 UTC by gizeasy

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются переменные из UI-kit
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://consta-widgets.consta.vercel.app/?path=/docs/common-develop-commits-style--page)

2021-02-16 07:24 UTC, al-fyodorov requested changes
Посмотри комментарии к коммиту. UPD: перелинковал к коду в PR.

2021-02-16 07:25 UTC, al-fyodorov requested changes

2021-02-16 07:25 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +type PropsWithHTMLAttributes<Props, HTMLElement> = Props &
Куда удобнее писать:

```ts
import { HTMLAttributes } from 'react'

type Props = HTMLAttributes<HTMLDivElement> & {}
```

2021-02-16 07:25 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +  icon: React.FC<IconProps>
Тип через функцию удобнее:

```tsx
import { ReactNode } from 'react'

type Icon = (props: IconProps) => ReactNode
```

Так как по типизации функция не требует дополнительных полей из функционального компонента.

2021-02-16 07:25 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Желательно проксировать свойства рутового JSX элемента в комопнент
'Желательно' не описывает случаи когда это надо делать, а когда нет. Стоит подумать и добавить случаи исключения когда это не требуется, еще раз напомню что не стоит накручивать бесполезную функциональность из-за того что она уже где-то есть. Могут быть виджеты где это и не требуется.

2021-02-16 07:25 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Желательно оборачивать компоненты `React.forwardRef`, для возможности получения ссылки на DOM элемент.
Опять таки 'Желательно' не описывает обходимость добавления или не добавления этой функциональности. Однако в следующей строке уже есть упоминание про то, что нужно добавлять обязательно для тултипа. Нужно описать исключения. Для пончика например это бесполезно, так как он сам тултипом управляет, для статов примеров с тултипом не видел, однако при сильной необходимости его можно теперь добавить. Так может все же есть исключения?

2021-02-16 07:27 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +type PropsWithHTMLAttributes<Props, HTMLElement> = Props &
В виджетах точно не будет `as` так как на рутовом компоненте в основном многие моменты завязаны.

2021-02-16 07:28 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Желательно оборачивать компоненты `React.forwardRef`, для возможности получения ссылки на DOM элемент.
И как бы место отображения на статах для тултипа можен не подходить, и в последствии его могут захотеть добавить в сами статы на блок с показателем изменнений, и тогда это оборачивание было бесполезным.

2021-02-16 07:30 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Желательно проксировать свойства рутового JSX элемента в комопнент
Если будете переносить BarChart вижу еще поинт в том чтобы оставить возможность aria атрибутов, но например onClick на самом графике кажется в большистве кейсов бесполезным, так как нас скорее будет интересовать конкретная группа или конкретный столбец. Так может разница все же есть добавлять везде или под конкретные кейсы?

2021-02-16 08:24 UTC, arhayka commented
Проверила и поправила текст во всём документе (опечатки, согласование, оформление). По смыслу и структуре старалась ничего не менять, но могу, если надо )))

2021-02-17 07:12 UTC, al-fyodorov requested changes

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +type Icon = (props: IconProps) => ReactNode
```suggestion
import { ReactElement } from 'react'

import { IconProps } from '@consta/uikit/Icon'

type Icon = (props: IconProps) => ReactElement | null
```

Поправил тип если возвращать `ReactElement | null`, то его можно будет создавать через `React.createElement`, что в большинстве случаев будет спасать от странных багов.

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +const Component: React.FC<ComponentProps> = ({ label, className, otherProps }) => (
```suggestion
type Props = HTMLAttributes<HTMLDivElement> & {
  label: React.FC<IconProps>
}

const cnComponent = cn('Component')

const Component: React.FC<Props> = ({ label, className, otherProps }) => (
```

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +const Component: React.FC<ComponentProps> = ({ label, className, otherProps }) => (
Пример был сломан так как просто `HTMLAttributes` ничего не дают, а `Props` при этом не используются.

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Стоит проксировать свойства рутового JSX элемента в компонент, если есть необходимость прокидывать атрибуты.
В итоге вместо `Стоит, Желательно` и других вариантов которые не описывают правило нужно получить текст вида: `Если компонент A соответствует требованиям B, C и D, тогда необходимо обязательно прокидывать атрибуты корневого элемента и указывать их в Props как в примере ниже`. Все остально никак не описывает это правило, кроме как добавляй всегда и не думай.

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +К примеру если это небольшой компонент которому не помешают свойства рутового элемента,
Как определяется параметр "небольшой"? Все старые виджеты довольно развесистые с кучей логики, разве что только `Stats` подходил по определению к "небольшой". Получается только в `Stats` это требуется, а в остальных не нужно?

2021-02-17 07:12 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Необходимо оборачивать компоненты `React.forwardRef` для возможности получения ссылки на DOM-элемент, если предпологается что такая необходимость вероятна.
Кем, когда и как это должно предполагаться? Заранее не предугадать всех кейсов, тот же тултип в Stats могут захотеть отображать у показателя изменений для расшифровки, и тогда ссылка на корневой элемент другому разработчику не нужна, нужна ссылка на элемент для `rate`, но так как мы этого не учли, то прокинули только на корень.

Возможно такие моменты стоит обговаривать на уровне самого дизайна, где как и при каких обстоятельствах могут потребоваться тултипы, поповеры и прочие элементы для подсказок, если их в изначальных макетах нет, то такое поведение не предполагается, и тогда оборачивать просто так в forwardRef бесполезно и не требуется.

Вот тебе простое правило, но надо еще подумать и выписать подобные кейсы и требования когда и почему мы это делаем, а не потому что так везде.

2021-02-17 10:43 UTC, gizeasy commented on docs/developers/arrangements-for-code-style.mdx
> +Необходимо оборачивать компоненты `React.forwardRef` для возможности получения ссылки на DOM-элемент, если предпологается что такая необходимость вероятна.
Хорошая идея обговаривать как и где компонент будет использоваться при дизайне, но думаю что не все кейсы возможно предугадать именно по этому думаю добавлять возможность взять ссылку на элемент на всякий случай. Но можно и убрать это правило, и не добавлять `ref` пока это действительно не понадобиться. Но также есть вероятность того что это понадобиться но человек просто не создаст ишью и будет обходиться тем что имеет. Мы же библиотеку делаем не только для себя и для наших проектов, и думаю что нам может казаться на первый взгляд излишним, возможно для кого-то покажется необходимостью

2021-02-17 10:46 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Необходимо оборачивать компоненты `React.forwardRef` для возможности получения ссылки на DOM-элемент, если предпологается что такая необходимость вероятна.
Тогда формулировка должна быть другой, оборачиваем все, без вычисления необходимостей и вероятностей.

2021-02-17 11:09 UTC, gizeasy commented on docs/developers/arrangements-for-code-style.mdx
> +Стоит проксировать свойства рутового JSX элемента в компонент, если есть необходимость прокидывать атрибуты.
затрудняюсь конкретизировать правило. Но думаю не помешает проксировать все атрибуты во все компоненты. Такие свойства как className, style и aria-атрибуты очень часто используются и при разработке просто можно забыть их проставить, так же мы можем не учесть какой-ни-буть кейс наведения мыши на наш компонент чтоб отработал колбек для изменения чего-ни-буть в проекте. И эта функциональность компонента ни как ни влияет на вид (кроме className, style) и внутреннюю логику компонента, но делает его гибче в заимодействии с внешним миром.

2021-02-17 11:32 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +Стоит проксировать свойства рутового JSX элемента в компонент, если есть необходимость прокидывать атрибуты.
Тогда так и надо описать, что это нужно и пункты для чего и что это обязательно, а не просто стоит так делать. Требования должны быть четко сформулированны, чтобы они соблюдались.

2021-02-18 07:53 UTC, al-fyodorov requested changes

2021-02-18 07:53 UTC, al-fyodorov commented on docs/developers/arrangements-for-code-style.mdx
> +const Component: Component = React.forwardRef(({ label, className, ...otherProps }, ref) => (
А зачем мы тут указываем `React.RefAttributes`, если мы и так из React-а получили все пропсы `HTMLDivElement`? Если смотреть по типизации то `HTMLDivElement` наследуется от `HTMLElement`, а тот в свою очередь от Element.

Кроме того зачем-то создается тип с названием компонента, если правильно указать в `forwardRef` типизацию, то дальше `TypeScript` сам выведет правильный `inline` тип. А такой подход с одинаковым названием переменной и типа чаще приводит к ошибке.

В таком случае правильным вариантом будет:
```tsx
type Props = HTMLAttributes<HTMLDivElement> & {
  label: React.FC<IconProps>
}

const cnComponent = cn('Component')

const Component: Component = forwardRef<HTMLDivElement, Props>(({ label, className, ...otherProps }, ref) => (
```

И это отлично работает, зачем усложнять себе жизнь описывая бесполезные типы?

2021-02-18 08:08 UTC, al-fyodorov approved these changes

2021-02-18 09:11 UTC, arhayka commented on docs/developers/arrangements-for-code-style.mdx
> +## Проксирование свойств корневого элемента компонента и добавление возможность получения ссылки на DOM-элемент
## Проксирование свойств корневого элемента компонента и возможность получения ссылки на DOM-элемент

2021-02-18 09:13 UTC, arhayka commented on docs/developers/arrangements-for-code-style.mdx
> +Необходимо проксировать свойства рутового JSX элемента и оборачивать компонент в `React.forwardRef` для повышения гибкости взаимодействия с компонентом
1. JSX-элемента 
или 
элемента JSX

2. точечка нужна в конце предложения

2021-02-18 09:14 UTC, arhayka commented on docs/developers/arrangements-for-code-style.mdx
> +Для повышения гибкости взаимодействия с компонентом.
Вот тут поломалось что-то. 

Необходимо оборачивать компоненты `React.forwardRef, чтобы можно было получить ссылку на DOM-элемент. Это нужно для повышения гибкости взаимодействия с компонентом.

2021-02-18 11:04 UTC, merged